# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
   kafka2:
     container_name: kafka2
     hostname: kafka2
     image: hyperledger/fabric-kafka
     restart: always
     environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_HEAP_OPTS=-Xmx256M -Xms128M
     ports:
      - "9092:9092"
     extra_hosts:
      - "zookeeper1:172.20.6.145"
      - "zookeeper2:172.20.6.151"
      - "zookeeper3:172.20.6.147"
      - "kafka1:172.20.6.146"
      - "kafka2:172.20.6.144"
      - "kafka4:172.20.6.198"


