# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
# 
# ZooKeeper的基本运转流程：
# 1、选举Leader。
# 2、同步数据。
# 3、选举Leader过程中算法有很多，但要达到的选举标准是一致的。
# 4、Leader要具有最高的执行ID，类似root权限。
# 5、集群中大多数的机器得到响应并follow选出的Leader。
#

version: '2'

services:

  zookeeper3:
    container_name: zookeeper3
    hostname: zookeeper3
    image: hyperledger/fabric-zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper1:2988:3888 server.2=zookeeper2:2988:3888 server.3=zookeeper3:2988:3888
    ports:
      - "2181:2181"
      - "2988:2988"
      - "3888:3888"
    extra_hosts:
      - "zookeeper1:172.20.6.145"
      - "zookeeper2:172.20.6.151"
      - "zookeeper3:172.20.6.147"
      - "kafka1:172.20.6.146"
      - "kafka2:172.20.6.144"
      - "kafka4:172.20.6.198"
